steps:
- name: node:10.15.1
  entrypoint: yarn
  args: ["install"]
- name: node:10.15.1
  entrypoint: yarn
  args: ["build"]
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["app", "deploy"]
# timeout: "1600s"
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'